---
- name: Install Cockpit package
  ansible.builtin.dnf:
    name: cockpit
    state: present
    update_cache: yes

- name: Ensure cockpit.socket is enabled and running
  ansible.builtin.service:
    name: cockpit.socket
    state: started
    enabled: yes

- name: Open Cockpit port in firewalld
  ansible.builtin.firewalld:
    service: cockpit
    permanent: yes
    state: enabled
    immediate: yes