---
- name: Install Cockpit packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - cockpit
    - cockpit-machines

- name: Ensure cockpit.socket is enabled and running
  ansible.builtin.service:
    name: cockpit.socket
    state: started
    enabled: yes

- name: Open Cockpit port in firewalld
  ansible.builtin.firewalld:
    service: cockpit
    permanent: yes
    state: enabled
    immediate: yes